"""Compose workflow - THE META-WORKFLOW: nine builds nine.

Given a task ("build a workflow that triages issues"), compose runs a
6-node pipeline: spec (ADK -> SPEC.md + WF_ID.txt), structure-design
(ADK -> HOP_SPEC.json), implement (ADK -> generated plugin module in
nine/chains/plugins/), test (bash: compile + import + hop structure),
register (bash: append to plugin_registry.py), validate (bash: fresh
registry import confirms the id is executable). Model-or-fail at every
model node; the gate decides SHIP/FIX/BLOCK from artifacts.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from nine.chains.chain import Hop
from nine.gates.evidence import (
    eval_json_check,
    exit_codes_check,
    required_artifact_check,
)
from nine.runtime.fsafety import contained_write
from nine.runtime.llm_provider import key_available
from nine.runtime.workflows import Node, Workflow, WorkflowError

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_PLUGINS_DIR = _REPO_ROOT / "nine" / "chains" / "plugins"
_DEFAULT_REG = _PLUGINS_DIR / "plugin_registry.py"


def _require_key(lane: str) -> None:
    if not key_available():
        raise WorkflowError(
            f"{lane} requires an LLM key (gemini: GEMINI_API_KEY; openai: NINE_LLM_API_KEY/OPENCODE_GO_API_KEY) (ADK LlmAgent) - no offline "
            "fallback, nine is model-driven"
        )


def _sanitize_id(raw: str) -> str:
    """Lowercase snake_case, must not start with a digit."""
    out = re.sub(r"[^a-z0-9_]", "_", (raw or "").lower())
    if out and out[0].isdigit():
        out = "wf_" + out
    return out or "generated_wf"


# --- plugin template -------------------------------------------------------
# A complete, importable, minimal workflow. The implement node replaces the
# __WF_ID__ / __DESCRIPTION__ markers and customizes nodes per HOP_SPEC.json.
_PLUGIN_TEMPLATE = '''"""__DESCRIPTION__ -- generated by nine compose."""
from __future__ import annotations

from pathlib import Path

from nine.chains.chain import Hop
from nine.gates.evidence import (
    eval_json_check,
    exit_codes_check,
    required_artifact_check,
)
from nine.runtime.workflows import Node, Workflow


def _capture_command() -> str:
    return r"""
echo "task inputs captured" > DATA.md
ls -la >> DATA.md
exit 0
"""


def _validate_command() -> str:
    return r"""
python - <<'PYVAL'
import json
from pathlib import Path
ok = Path("DATA.md").exists() and Path("DATA.md").stat().st_size > 0
json.dump({"checks": [{"name": "__WF_ID__-validate", "passed": ok, "message": "DATA.md present" if ok else "DATA.md missing"}], "exit_code": 0 if ok else 1}, open("EVAL.json", "w"))
PYVAL
exit 0
"""


def __WF_ID___hop() -> Hop:
    """Generated workflow: __DESCRIPTION__."""
    wf = Workflow(id="__WF_ID__", description="__DESCRIPTION__")
    capture = Node(id="capture", kind="bash", command=_capture_command(),
                   description="Write DATA.md")
    validate = Node(id="validate", kind="bash", command=_validate_command(),
                    description="Write EVAL.json")
    validate.depends_on = ["capture"]
    for n in (capture, validate):
        wf.add_node(n)
    return Hop(
        id="__WF_ID__", workflow=wf,
        required_artifacts=["DATA.md", "EVAL.json"],
        gate_checks={
            "exit-codes": exit_codes_check(),
            "eval-json": eval_json_check(),
            "artifacts": required_artifact_check(["DATA.md", "EVAL.json"]),
        },
        max_fix_loops=2,
    )
'''


def _spec_tool_node() -> Node:
    """ADK LlmAgent: task -> SPEC.md + WF_ID.txt (the workflow design)."""
    def _run(inputs: dict, job_dir) -> dict:
        from nine.runtime.adk_runtime import ADKAgentNode

        job_dir = Path(job_dir)
        task = str(inputs.get("task", ""))[:500]
        _require_key("compose (spec)")

        from google.adk.agents import LlmAgent
        from google.adk.tools import FunctionTool

        from nine.runtime import llm_provider

        def write_file(path: str, content: str) -> str:
            contained_write(job_dir, path, content)
            return f"wrote {path} ({len(content)} bytes)"

        agent = LlmAgent(
            name="compose-spec",
            model=llm_provider.adk_model(),
            instruction=(
                "You are the spec designer of nine's compose meta-workflow. "
                "Design a small workflow (2-5 nodes) that accomplishes the "
                "task. Every node is either:\n"
                "- bash: deterministic data/file operations (find, parse, "
                "validate, write markdown/json). Give each bash node a "
                "one-line description of what it produces.\n"
                "- tool: a model step (ADK LlmAgent with write_file) for "
                "reasoning about content - note this in the description.\n"
                "Write SPEC.md: title, purpose, the node list with ids "
                "(snake_case), kinds, and per-node outputs, the final "
                "artifacts the workflow must produce, and what the gate "
                "should check (EVAL.json + required artifacts).\n"
                "Then write WF_ID.txt containing ONLY the lowercase "
                "snake_case workflow id (letters, digits, underscore, not "
                "starting with a digit), e.g. `issue_triage`.\n"
                f"Task: {task}\n"
            ),
            tools=[FunctionTool(write_file)],
        )
        return ADKAgentNode(agent)(inputs, job_dir)

    return Node(
        id="spec", kind="tool", run=_run,
        max_retries=2, retry_delay_seconds=1.0,
        description="ADK LlmAgent writes SPEC.md + WF_ID.txt",
    )


def _structure_tool_node() -> Node:
    """ADK LlmAgent: SPEC.md -> HOP_SPEC.json (machine-readable design)."""
    def _run(inputs: dict, job_dir) -> dict:
        from nine.runtime.adk_runtime import ADKAgentNode

        job_dir = Path(job_dir)
        _require_key("compose (structure-design)")

        from google.adk.agents import LlmAgent
        from google.adk.tools import FunctionTool

        from nine.runtime import llm_provider

        def write_file(path: str, content: str) -> str:
            contained_write(job_dir, path, content)
            return f"wrote {path} ({len(content)} bytes)"

        spec = ""
        p = job_dir / "SPEC.md"
        if p.exists():
            spec = p.read_text(encoding="utf-8")[:4000]
        wfid_raw = ""
        p = job_dir / "WF_ID.txt"
        if p.exists():
            wfid_raw = p.read_text(encoding="utf-8").strip()

        agent = LlmAgent(
            name="compose-structure",
            model=llm_provider.adk_model(),
            instruction=(
                "You are the structure designer of nine's compose "
                "meta-workflow. Turn SPEC.md into HOP_SPEC.json - a "
                "machine-readable design the implementer will code from. "
                "Exact schema (valid JSON, nothing else in the file):\n"
                '{"workflow_id": "<lowercase snake_case>", '
                '"description": "<one line>", '
                '"nodes": [{"id": "<snake>", "kind": "bash|tool", '
                '"description": "<what it produces>"}], '
                '"required_artifacts": ["<file>", ...], '
                '"max_fix_loops": 2}\n'
                "Rules: workflow_id must be lowercase snake_case, not "
                "starting with a digit; every node has a unique id; every "
                "artifact listed is a filename the workflow will write; at "
                "least one node must write EVAL.json (the gate reads it). "
                "Use the workflow id from WF_ID.txt if it is valid, else "
                "fix it. Write ONLY the JSON to HOP_SPEC.json.\n"
                f"SPEC.md:\n{spec}\n"
                f"WF_ID.txt: {wfid_raw}\n"
            ),
            tools=[FunctionTool(write_file)],
        )
        return ADKAgentNode(agent)(inputs, job_dir)

    return Node(
        id="structure-design", kind="tool", run=_run,
        max_retries=2, retry_delay_seconds=1.0,
        description="ADK LlmAgent writes HOP_SPEC.json",
    )


def _implement_tool_node() -> Node:
    """ADK LlmAgent: HOP_SPEC.json -> generated plugin module."""
    def _run(inputs: dict, job_dir) -> dict:
        from nine.runtime.adk_runtime import ADKAgentNode

        job_dir = Path(job_dir)
        _require_key("compose (implement)")

        from google.adk.agents import LlmAgent
        from google.adk.tools import FunctionTool

        from nine.runtime import llm_provider

        def write_file(path: str, content: str) -> str:
            if path.endswith("_wf.py"):
                # torture-7 F3: never overwrite an existing plugin module
                # (built-in or previously composed) — a collision must fail
                # the job, not silently hijack a lane.
                target = Path(_PLUGINS_DIR) / path
                if target.exists():
                    return (f"REFUSED: {path} already exists in the plugins "
                            f"dir — pick a different WF_ID; nine never "
                            f"overwrites an existing plugin")
                contained_write(Path(_PLUGINS_DIR), path, content)
                contained_write(job_dir, path, content)
                return (f"wrote {path} to plugins dir + job dir "
                        f"({len(content)} bytes)")
            contained_write(job_dir, path, content)
            return f"wrote {path} ({len(content)} bytes)"

        hop_spec = ""
        p = job_dir / "HOP_SPEC.json"
        if p.exists():
            hop_spec = p.read_text(encoding="utf-8")[:5000]

        agent = LlmAgent(
            name="compose-implement",
            model=llm_provider.adk_model(),
            instruction=(
                "You are the implementer of nine's compose meta-workflow. "
                "Generate a complete, importable Python workflow module "
                "from the template below by replacing every __WF_ID__ "
                "occurrence with the workflow_id from HOP_SPEC.json and "
                "every __DESCRIPTION__ with its description. Then adapt "
                "the node ids, commands, artifacts and gate checks to "
                "HOP_SPEC.json (you may add nodes; bash nodes need real "
                "shell commands; tool nodes are declared with kind='tool' "
                "and a description only - they run as ADK LlmAgents).\n"
                "Hard rules:\n"
                "- The file must define a function named "
                "<workflow_id>_hop() returning a Hop.\n"
                "- Every node id unique; validate node(s) write EVAL.json "
                "with checks + exit_code (0 when passed).\n"
                "- Keep the imports and the Hop/Workflow/Node API exactly "
                "as in the template.\n"
                "- Valid Python - it will be compiled and imported; syntax "
                "errors fail the gate.\n"
                f"HOP_SPEC.json:\n{hop_spec}\n"
                f"TEMPLATE:\n{_PLUGIN_TEMPLATE}\n"
            ),
            tools=[FunctionTool(write_file)],
        )
        return ADKAgentNode(agent)(inputs, job_dir)

    return Node(
        id="implement", kind="tool", run=_run,
        max_retries=2, retry_delay_seconds=1.0,
        description="ADK LlmAgent writes the plugin module into nine/chains/plugins/",
    )


# --- bash nodes --------------------------------------------------------------
def _test_command() -> str:
    """Bash: compile + import + construct the generated hop."""
    py = r'''
import importlib.util
import sys

wfid, path = sys.argv[1], sys.argv[2]
ok = True
msgs = []
try:
    import py_compile
    py_compile.compile(path, doraise=True)
    msgs.append("compiles")
    spec = importlib.util.spec_from_file_location(f"{wfid}_wf", path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    msgs.append("imports")
    factory = getattr(mod, f"{wfid}_hop")
    hop = factory()
    assert len(hop.workflow.nodes) >= 1, "no nodes"
    assert hop.gate_checks, "no gate checks"
    for nid, n in hop.workflow.nodes.items():
        if n.kind == "bash" and not n.command:
            raise AssertionError(f"node {nid} missing command")
    msgs.append(f"hop OK ({len(hop.workflow.nodes)} nodes, {len(hop.gate_checks)} checks)")
except Exception as exc:  # noqa: BLE001 - gate decides from the report
    ok = False
    msgs.append(f"FAIL: {exc}")
open("TEST_RESULTS.md", "w").write(
    "\n".join(["# Test", f"- plugin: {path}", "- " + "\n- ".join(msgs) if ok else str(msgs)])
)
if ok:
    open("TEST_PASS", "w").write("ok")
'''
    return (
        "\n"
        "WFID=$(cat WF_ID.txt | tr 'A-Z' 'a-z' | sed 's/[^a-z0-9_]/_/g' | sed 's/^[0-9]/wf_&/')\n"
        f"PLUGIN=\"{_PLUGINS_DIR}/${{WFID}}_wf.py\"\n"
        "python - \"$WFID\" \"$PLUGIN\" <<'PYCOMPOSE'\n"
        + py
        + "PYCOMPOSE\n"
        "exit 0\n"
    )


def _register_command() -> str:
    """Bash: append the plugin factory to plugin_registry.py (idempotent)."""
    py = r'''
import sys

wfid, reg = sys.argv[1], sys.argv[2]
with open(reg, encoding="utf-8") as f:
    txt = f.read()
line = f"from nine.chains.plugins.{wfid}_wf import {wfid}_hop"
if line not in txt:
    with open(reg, "a", encoding="utf-8") as f:
        f.write(f"\n{line}\n")
        f.write(f'PLUGIN_WORKFLOWS["{wfid}"] = {wfid}_hop\n')
    status = "registered"
else:
    status = "already registered"
open("REGISTER.md", "w", encoding="utf-8").write(
    f"# Register\n\n{status}: {wfid} -> {reg}\n"
)
'''
    return (
        "\n"
        "WFID=$(cat WF_ID.txt | tr 'A-Z' 'a-z' | sed 's/[^a-z0-9_]/_/g' | sed 's/^[0-9]/wf_&/')\n"
        'REG="${NINE_PLUGIN_REGISTRY:-' + str(_DEFAULT_REG) + '}"\n'
        "if [ -f TEST_PASS ]; then\n"
        "  python - \"$WFID\" \"$REG\" <<'PYREGISTER'\n"
        + py
        + "PYREGISTER\n"
        "else\n"
        "  echo \"test did not pass; skipping registration\" > REGISTER.md\n"
        "fi\n"
        "exit 0\n"
    )


def _validate_command() -> str:
    """Bash: fresh registry import confirms the workflow is executable."""
    py = r'''
import json
import sys

wfid = sys.argv[1]
try:
    import nine.registry as reg
    ok = wfid in reg.WORKFLOWS
    msg = f"registered and executable: {wfid}" if ok else f"NOT registered: {wfid}"
except Exception as exc:  # noqa: BLE001 - gate decides from EVAL.json
    ok = False
    msg = f"registry import failed: {exc}"
json.dump({"checks": [{"name": "compose-validate", "passed": ok, "message": msg}],
           "exit_code": 0 if ok else 1}, open("EVAL.json", "w"))
'''
    return (
        "\n"
        "WFID=$(cat WF_ID.txt | tr 'A-Z' 'a-z' | sed 's/[^a-z0-9_]/_/g' | sed 's/^[0-9]/wf_&/')\n"
        f"PYTHONPATH={_REPO_ROOT} python - \"$WFID\" <<'PYVALIDATE'\n"
        + py
        + "PYVALIDATE\n"
        "exit 0\n"
    )


def _compose_check(ctx: dict[str, Any], workdir: Path) -> tuple[bool, str]:
    """The generated plugin must exist in the repo AND in the job dir.

    torture-7 F3: a plugin id that collides with a BUILT-IN workflow/chain
    id (or an existing plugin file) must be refused here — WORKFLOWS.update
    would silently replace the production lane with the plugin under the
    built-in gate. Refusing at the gate keeps the built-in lane intact and
    BLOCKs the compose job with a clear reason.
    """
    wd = Path(workdir)
    wfid = "generated_wf"
    p = wd / "WF_ID.txt"
    if p.exists():
        wfid = _sanitize_id(p.read_text(encoding="utf-8").strip())
    try:
        # built-in ids = WORKFLOWS/CHAINS minus plugin-loaded ids: by the
        # time the gate runs, THIS run's register node already appended the
        # plugin to the registry, so a naive `wfid in WORKFLOWS` would
        # falsely flag the run's own (legitimate) plugin as a collision.
        from nine.registry import CHAINS, WORKFLOWS, _load_plugin_workflows

        plugin_ids = set(_load_plugin_workflows())
        builtin_ids = (set(WORKFLOWS) - plugin_ids) | set(CHAINS)
        if wfid in builtin_ids:
            return False, (f"id collision: '{wfid}' is a BUILT-IN workflow/"
                           f"chain id — refusing to install a plugin over a "
                           f"production lane (pick another WF_ID)")
    except Exception as exc:  # noqa: BLE001 - never crash the gate
        return False, f"cannot check id collisions: {exc}"
    existing = _PLUGINS_DIR / f"{wfid}_wf.py"
    job_copy = wd / f"{wfid}_wf.py"
    if existing.exists() and not job_copy.exists():
        # the file pre-existed and THIS run did not produce it (a stale
        # leftover or another run's plugin): refuse to overwrite.
        return False, (f"id collision: {existing.name} already exists in the "
                       f"plugins dir and was not produced by this run — "
                       f"refusing to overwrite an existing plugin (pick "
                       f"another WF_ID or remove it first)")
    repo_file = _PLUGINS_DIR / f"{wfid}_wf.py"
    if not repo_file.exists():
        return False, f"{wfid}_wf.py missing in plugins dir"
    size = repo_file.stat().st_size
    if size < 100:
        return False, f"{wfid}_wf.py too small ({size} bytes)"
    job_copy = wd / f"{wfid}_wf.py"
    if not job_copy.exists():
        return False, f"{wfid}_wf.py missing in job dir"
    # torture-17 F2: declare the exact job-dir files certified (dynamic
    # name — the tag must be set at call time to match THIS run's wfid).
    _compose_check.expected = [  # type: ignore[attr-defined]
        "WF_ID.txt", f"{wfid}_wf.py"]  # torture-17 F2 tag
    return True, f"{wfid}_wf.py present ({size} bytes)"


def compose_hop() -> Hop:
    """The `compose` workflow: nine builds nine.

    1. spec (tool)             - SPEC.md + WF_ID.txt
    2. structure-design (tool) - HOP_SPEC.json
    3. implement (tool)        - plugin module in nine/chains/plugins/
    4. test (bash)             - compile + import + hop structure
    5. register (bash)         - append to plugin_registry.py
    6. validate (bash)         - fresh registry import -> EVAL.json

    Gate: EVAL passed + plugin file present + artifacts + exits.
    """
    wf = Workflow(id="compose",
                  description="THE META-WORKFLOW: nine builds nine "
                              "(spec -> structure -> implement -> test -> register)")
    spec = _spec_tool_node()
    structure = _structure_tool_node()
    structure.depends_on = ["spec"]
    implement = _implement_tool_node()
    implement.depends_on = ["structure-design"]
    test = Node(id="test", kind="bash", command=_test_command(),
                description="Compile + import the generated plugin")
    test.depends_on = ["implement"]
    register = Node(id="register", kind="bash", command=_register_command(),
                    description="Append plugin to plugin_registry.py")
    register.depends_on = ["test"]
    validate = Node(id="validate", kind="bash", command=_validate_command(),
                    description="Fresh registry import -> EVAL.json")
    validate.depends_on = ["register"]
    for n in (spec, structure, implement, test, register, validate):
        wf.add_node(n)
    return Hop(
        id="compose", workflow=wf,
        required_artifacts=["WF_ID.txt", "SPEC.md", "HOP_SPEC.json",
                            "TEST_RESULTS.md", "REGISTER.md", "EVAL.json"],
        gate_checks={
            "eval-json": eval_json_check(),
            "exit-codes": exit_codes_check(),
            "artifacts": required_artifact_check(
                ["WF_ID.txt", "SPEC.md", "HOP_SPEC.json",
                 "TEST_RESULTS.md", "REGISTER.md", "EVAL.json"]
            ),
            "plugin": _compose_check,
        },
        max_fix_loops=2,
    )
